### PR TITLE
Fixed ellipsis

### PR DESCRIPTION
**Pull request by urbalazs**
Hello @Rijackson
I tried to fix all ellipsis with this pull request, as we discussed in https://github.com/Zukero/andors-trail/issues/76. Sorry for the huge change, but there are many occurrences. Please review it, and leave a message if I have to change anything.

Please push the strings to **Weblate** after the merge, because hundreds of strings were changed in the last few days. Translators need some time to adapt their translations.

### CODE REVIEW

**Comment by Zukero** [comment]
I'll do what I did last time I updated weblate: I'll preserve the existing translations, updating only the English string, while pointing to the existing translation from the new English ones. Syntax rules vary from one language to another, so a fix in English doesn't imply that the translations must be updated too.
This is a lengthy process, so I'll do it when I have the chance to do it.

**Comment by Zukero** [comment]
His Wikipedia search did note that between words, the ellipsis is surrounded by two spaces.

**Comment by Rijackson** [comment]
If those two words are in a single sentence. If it's at the end of the sentence there is no space.

Different style guides give different suggestions though, so I think the main thing is that it's consistent, which it now is.

**Comment by urbalazs** [comment]
Thank you for your feedback! All suggestions are fixed with https://github.com/Zukero/andors-trail/pull/78/commits/e2ab2d484b323707cbc80c24a7fbd544f0b17d24, except your first suggestion, as there is already an "A" after the new line: \n**A** rose ... I need my rose.
This also fixes "Aryforas father" -> Aryfora's father
This pull request can be merged now, I think. Can you check it?

**Comment by Rijackson** [comment]
OK. Great :)

**Pull request merged**
