### PR TITLE
Mikhail

### PR DESCRIPTION
**Pull request by carceris-magister**
Changed Mikhail's opening dialog to be more aware of context. If the character has completed one of the quests, Mikhail knows about it and there's not an option to ask about it again. Also don't repeat the opening sequence "I can't seem to find your brother anywhere..." every time the character starts a conversation (the background is still available again by asking).

### CODE REVIEW

**Comment by carceris-magister** [comment]
I'd be interested in feedback on this one. Is there a more efficient way to make the changes?

In any case, please try it out with a new character. I think it gives a more-polished impression for a new player's first NPC interactions, without changing the gameplay in any way.

**Comment by Zukero** [comment]
I'll review it in ATCS soon. In the meantime, you can add yourself to the Authors file in this branch.

**Comment by Rijackson** [comment]
I can't import it into ATCS. It throws an error if I try.

**Comment by davidmegginson** [comment]
OK, I'll take a look in ATCS. It ran fine in the app, but I'm not good with visual tools (the JSON makes a lot more sense to me than all the lines and nodes in ATCS).

**Comment by Rijackson** [comment]
The problem is the lines that say 
"negate":"true"

**Comment by Zukero** [comment]
Indeed, those should be "negate":true
No quotes around true.

2017-08-18 0:45 GMT+02:00 Rijackson <notifications@github.com>:

**Comment by carceris-magister** [comment]
Got it! I was copying the quoted version from what I'd seen in a message in the forum. Will fix in this branch.

**Comment by carceris-magister** [comment]
I fixed the booleans, and successfully opened it in ATCS. Feel free to give it another try.

**Comment by Rijackson** [comment]
mikhail_rats_start2 used to lead to mikhail_rats_start3. You have it leading to mikhail_rats_start2a, which does not exist.

**Comment by carceris-magister** [comment]
@Rijackson 
That was already committed before I made my changes. You can find the additional dialog in conversationlist_mikhail_foodpoison.json

**Comment by Rijackson** [comment]
Yes, my bad. The sources the project points to do not have that commit.

**Comment by Zukero** [comment]
As per @rijackson 's review, I'm about to merge this, after you added yourself to the authors file or explicitly refuse to do so. Thanks for submitting this.

**Comment by Rijackson** [comment]
In case you don't know where that is, to save you some time: "AndorsTrail\res\values\authors.xml"

**Comment by Gulisano** [comment]
Sorry, is this request for me?

- Mike

**Comment by Zukero** [comment]
Nope. It was for @carceris-magister

Le 18 déc. 2017 21:21, "Gulisano" <notifications@github.com> a écrit :

Sorry, is this request for me?

- Mike

On 12/17/17, Zukero <notifications@github.com> wrote:
> As per @rijackson 's review, I'm about to merge this, after you added
> yourself to the authors file or explicitly refuse to do so. Thanks for
> submitting this.
>
> --

> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Zukero/andors-trail/pull/33#issuecomment-352284379

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Zukero/andors-trail/pull/33#issuecomment-352546494>,
or mute
the thread

**Pull request merged**
