### PR TITLE
Tidied JSON files

### PR DESCRIPTION
**Pull request by urbalazs**
Hello @Zukero 
Some JSON files have CRLF or LF line terminators. I fixed them, so now every file has the same line terminators. I also tidied some files with jq, which is a [command line JSON processor](https://stedolan.github.io/jq/).
With this pull request no logic is changed, only the JSON files are tidied.

### CODE REVIEW

**Comment by urbalazs** [comment]
If a file has CRLF or LF line terminators, then using `sed` for changing something or using `gedit` (default text editor in Ubuntu) will break the line terminators, and insert a ^M character to each modified lines. If a file has Unix line terminators, then both `sed` and `gedit` works well. Only this few files are different, so I don't think, that ATCS will cause huge diff.

**Comment by Rijackson** [comment]
A lot of spaces have been removed. For example, "id": "chaotic_grip", is now "id":"chaotic_grip". I suspect that ATCS will put those back.

**Comment by urbalazs** [comment]
I don't think so.
With space: `grep -ho '": ' AndorsTrail/res/raw/*.json | wc -l` occurs 540 times
Without space: `grep -ho '":' AndorsTrail/res/raw/*.json | wc -l` occurs 66.501 times

**Comment by Rijackson** [comment]
Yeah, I just looked at the diff for the first file, but now I realize that's actorconditions_debug.json. You see the same thing in conversationlist_debug.json. The effect on the debug files doesn't matter. 

But what did it do in conversationlist_trader_teksin.json? The diff seems to be much larger than it needs to be.

**Comment by urbalazs** [comment]
> But what did it do in conversationlist_trader_teksin.json?

It changed the line terminations, so all lines are changed, because:
`AndorsTrail/res/raw/conversationlist_trader_teksin.json: ASCII text, with very long lines, with CRLF, LF line terminators`

**Comment by Rijackson** [comment]
Ah. I see. That file was entirely created by ATCS (I created it). That makes me wonder what will happen if I edit some of Teksin's dialogue, and export the json file again.

**Comment by urbalazs** [comment]
Maybe it was created on Windows? You can check the line terminators with this command:
`file AndorsTrail/res/raw/*.json`

In the current master branch these files have "Windows" (`\r\n`) line terminators:

- AndorsTrail/res/raw/conversationlist_fallhaven_south.json
- AndorsTrail/res/raw/conversationlist_pathway_fallhaven.json
- AndorsTrail/res/raw/conversationlist_stoutford_combined.json
- AndorsTrail/res/raw/conversationlist_trader_teksin.json
- AndorsTrail/res/raw/questlist_pathway_fallhaven.json

I changed all the line terminators to "Unix" (`\n`), that is the reason of the huge diff. The other files have already `\n` terminators.

**Comment by Rijackson** [comment]
Interesting. I had never looked. The file was indeed created under Windows, but ATCS could write whatever line terminator it wants. I think we should wait for Zukero to weigh in on this, and explain how ATCS will handle this. Avoiding huge diffs for minor edits is important, but I think ATCS must already handle this line terminator problem by leaving them as is, whatever they are, during export.

**Comment by Zukero** [comment]
It's not only ATCS (which uses the system default line terminator AFAIK), but also your git client settings. You can set up git to always commit with \n or as-is. There is a similar setting for the checkout.

I'd say consistency with \n would be nice, but in the end, the most important is how each of us set up git locally.

**Comment by Rijackson** [comment]
I use Smartgit, and the default is that when I pull it changes all line terminators to the local default CRLF. I can change that, although from what I have read on-line others have had some troubles getting it to work. The editor I use is Notepad++, which also defaults to CRLF. I can change the line terminator in Notepad++, but I think that is only for new files. I believe that for existing files it will honor whichever line terminator is being used. So then for me the elephant in the room would be ATCS, because it will export files with CRLF (and I do not know how it will handle reading files with only LF; I have never tried). I can use Notepad++ to then do a global replace of CRLF to LF, but it would be one extra step.

What would be better would be to allow Smartgit to change all terminators to CRLF on pull, and change them all to LF on push. I don't know how to do that though. I do know that Smartgit uses the .gitconfig file for many preferences.

**Comment by urbalazs** [comment]
I assume, that you are using Windows, where the default terminator is CRLF for new files regardless the software used. Notepad++ keeps the actual line terminators so if we have Unix terminators, then modifying and saving this file with Notepad++ will keep the terminators.

Please merge this pull request if you would like, that all files have the same terminators, or close it without merge. I'd like to fix other issues, but these files may be affected.

**Comment by Rijackson** [comment]
For Notepad++, yes, it will preserve the line terminators. ATCS will not though. 

Locally, does this even matter? From what I have read the default behavior of git is to replace the line terminators to the local default when you pull. So if you pull to a Windows system they will all be CRLF. If you pull to a Linux system they will all be LF. What concerns me is what happens when you push, and I don't know the answer to that. If it preserves the local line terminator (which, given the huge diff in conversationlist_trader_teksin.json, appears to be the case) then that could be a problem. You change all the line terminators to LF. Then I make a tiny edit, and push back to github, and the entire file will show as the diff. That is really undesirable.

**Comment by Rijackson** [comment]
With some research, I agree with Zukero that what is important is how each person configures git. In the file .gitconfig I now have 
[core]
	autocrlf = true

When I pull from github all line terminations will be changed to CRLF. When I push to github they will all be changed to LF. As long as everyone has git configured to always push LF we will not see huge diffs there.

**Comment by Zukero** [comment]
Hello @urbalazs 
If you would undo the line terminator changes, I'll merge this.

**Comment by urbalazs** [comment]
This pull request was generated with a script, so it would be hard for me the remove some parts from it manually. I will create a new pull request without terminator changes. As no logic is changed, this is not so important for now. I close this PR.

**Pull request closed without merging**
