### PR TITLE
Fixed punctuation, trimmed strings, fixed typos

### PR DESCRIPTION
**Pull request by urbalazs**
Hello @Zukero 
I checked all the strings with `grep`, and I added the missing punctuation with this pull request. This also removed the superfluous white space characters from the end of strings.
A Weblate sync would be very welcome, as many strings are changed by this pull request.

### CODE REVIEW

**Comment by urbalazs** [comment]
> In the following strings:
> "You must have me mixed up with someone else."
> "Maybe you have me mixed up with my brother Andor."
> "Oh. I must have you mixed up with someone else."
> "Umar in the Fallhaven Thieves' Guild recognized me, but must have me mixed up with Andor. Apparently, Andor has been to see him."
> you replaced "mixed up" with "confused". But "mixed up" is very commonly used, probably more so than "confused" in this context. I think it is better as it was.

I replaced "mixed up" with "confused" to be the strings consistent with the following strings:
"You must have me confused with my brother Andor. We look very much alike."
"You must have me confused with someone else."
"Landa, you must have me confused with someone else! What was it you saw?"
"Landa confused me with someone else at first. ..."

What do you think, "mixed up" would be better than "confused"? If so, then I have to replace also in the latter strings. But I think, we can "mixed up" the ingredients, but "confused" people.

> In questlist_graveyard1.json, line 100, we have this curiosity: "I will have to pass though the forest to access an entrance to a cave northeast of Cithurn\u2019s home". I have no idea how that weird unicode character got there. It's not you doing (I checked the sources), but could you do me a favor and change it to a standard apostrophe.

Yeah, I will replace it in a separate pull request, because `grep -n 'u2019' * | wc -l` results 15 occurrences, so the mentioned Unicode (\u2019) are used in many strings.

> In conversationlist_stoutford_combined.json at lines 3093 and 4059, what changed? Git obviously thinks there's a difference, but I don't see it.

There were DOS line endings (CTRL-M character, carriage return), that I fixed, so that's why you don't see the different here. With the command `git diff` you can see the different. Now I checked with `grep "^M" * | wc -l`and it resulted 12431 occurrences (for typing ^M use CTRL+V, CTRL+M). I will create a separate pull request to fix the line endings. As I know, `dos2unix` can fix this.

**Comment by Rijackson** [comment]
> I replaced "mixed up" with "confused" to be the strings consistent with the following strings:
> "You must have me confused with my brother Andor. We look very much alike."
> "You must have me confused with someone else."
> "Landa, you must have me confused with someone else! What was it you saw?"
> "Landa confused me with someone else at first. ..."
> 
> What do you think, "mixed up" would be better than "confused"? If so, then I have to replace also in the latter strings. But I think, we can "mixed up" the ingredients, but "confused" people.

Looking at it from a purely logical point of view, I agree that mixing up people does not make a lot of sense (unless we are talking about a bad horror movie :D), but it's a common expression. However, I agree that Andor's brother would likely say it the same way each time. An NPC might not, but that is only one occurrence, "Oh. I must have you mixed up with someone else.". So flip a coin; some strings have to change either way. "confused" will work.

If you are looking for these kinds of problems, there is another one that is on my to-do list to fix. We have Ok, OK, and Okay. Ok is the most common, but it is not the correct spelling. Either OK or Okay are acceptable spellings (I won't get into why; you can Google it if you care enough). Fixing this requires a little care. Okay has to be replaced with OK first (or we could get OKay!). Then Ok has to be replaced with OK, but there are words that start with Ok (I don't think any are used in AT, but I am not sure and checking that would be hard to do), so Ok should only be replaced if it's followed by a space or punctuation (.,;:?! should cover it).

**Comment by urbalazs** [comment]
Okay. :) I will create an other pull request to standardize the words from "Ok", "OK" to "Okay".
Let's turn back to this pull request. Can you merge this in the current state, or can you tell me exactly, what should I change in order to merge?

**Comment by urbalazs** [comment]
> Either OK or Okay are acceptable spellings

Hmm, I read some article about this topic. Now I'm completely confused. I can't decide what would be the suggested form: "OK" or "Okay". So please make your decision, and I will create a pull request for you. By second reading and according to your replace-chain you prefer "OK".

**Comment by Rijackson** [comment]
I would go with "OK".

**Pull request merged**
