### PR TITLE
Improved wording

### PR DESCRIPTION
**Pull request by urbalazs**
Hello @Zukero 
I found these suggestions in weblate (by Allan Nordhøy).

### CODE REVIEW

**Comment by urbalazs** [comment]
@Zukero can you merge this pull request?

**Comment by urbalazs** [comment]
@Zukero can you merge this? Just a wording improvement.

**Comment by Zukero** [comment]
Yup, sorry for the delay...

**Comment by Zukero** [comment]
You'll need to wait a bit before seeing it in weblate though. It is sometimes tricky to get those merges right while someone makes changes on weblate, which is almost always.

**Pull request merged**
