### PR TITLE
Repeatable quest

### PR DESCRIPTION
**Pull request by FlorianDoublet**
Added the posibility to make any quest repeatable.

When a repeatable quest is finished, it delete itself from the Player progress quest, so it can  redone as mush as you want.

### CODE REVIEW

**Comment by LucasDelvallet** [comment]
We have improved this method.

Any stage of a quest can now have a removeProgressReward, which will delete the specified progress from the current quest and every successor progress.

**Comment by Zukero** [comment]
I see two major weaknesses in this implementation:
#1 - It's confusing for content authors. Removing a questProgress should be no different than adding one. In this implementation, the way to remove a quest progress is to create a conversation phrase that will give a quest progress that will in turn remove another quest progress. Why not just create a new reward type (model.script.ScriptEffect.ScriptEffectType) ? This way, authors can decide to add or remove any quest progress the same way.
- It's broken. For example, quest step 20 serves to remove quest step 15. Once you reach quest step 20, it removes quest step 15 from your progress, but also step 17 while this isn't desirable. Quest Step IDs are numerical, but not necessarily ordered.

I'd say you went a very complicated way where a simpler one would have been better:
- Add "removeQuestProgress" in the ScriptEffect.ScriptEffectType enum
- Handle it in the ConversationController in a way similar to "questProgress" ("addRemoveQuestProgressReward(...)")
- Add "Player.removeQuestProgress(...)" in a way similar to "Player.addQuestProgress(...)". Makes for a much clearer API.

**Comment by LucasDelvallet** [comment]
We have corrected all our mistakes, now the removeQuestProgress is a conversation reward. It's much clearer and allow more possibilities for content creator.

**Comment by Zukero** [comment]
Looks good to me !
Thanks for keeping it up despite my rants. 
If I may add one last comment, it would be great to have the Player.removeQuestProgress(...) return a boolean: true if the progress was present and actually removed, false otherwise, just like Player.addQuestProgress(...).

**Comment by Zukero** [comment]
One more: the new value in the 'Requirement.RequirementType' enum is not needed. The requirement for this is a negated 'questProgress' requirement.

**Comment by Zukero** [comment]
And a final one: you can also add yourself (yourselves ?) to the res/values/authors.xml credits if you so desire.

**Comment by FlorianDoublet** [comment]
We think it's good this time.

**Pull request merged**
