### PR TITLE
Added random requirements for conversations

### PR DESCRIPTION
**Pull request by Chriz76**
The requirement will be randomly fulfilled. The value between 0 and 100 is the chance in percent. 

Example for a 30% chance:
```
"requires":[
    {
        "requireType":"random",
        "value":30
    }
```

### CODE REVIEW

**Comment by Chriz76** [comment]
requireID can now be empty in the json. Thats needed for the spentGold and random requirement.

This will now work:

```
"requires":[
    {
        "requireType":"random",
        "requireID":"random",
        "value":30
    }
```

**Comment by Chriz76** [comment]
Now the random requirement is also added to ATCS

**Comment by Chriz76** [comment]
Added ACTS integration

**Comment by Zukero** [comment]
I think it would be wise to use the "requireID" to hold the value as a string, so that we can leverage the chance parser used for the droplists to gain more flexibility (either a plain int interpreted as a percentage, either an x/y ratio of integers).
To ensure the format is correct, we'll use some UI-magic in ATCS.

**Comment by Chriz76** [comment]
I changed it to use the requireID and the same format as the dropitem Chance:

https://github.com/Chriz76/andors-trail/tree/randomrequirements

**Pull request closed without merging**
