### PR TITLE
Clean up English and change Glasforn dialogue

### PR DESCRIPTION
**Pull request by Rijackson**

### CODE REVIEW

**Comment by reizy** [comment]
There are many useless changes like:
-                 "nextPhraseID":"fallhaven_lumberjack_2",
-                "text":"Are you a woodcutter?"
+                "text":"Are you a woodcutter?",
+                "nextPhraseID":"fallhaven_lumberjack_2"

**Comment by Rijackson** [comment]
Yes. ATCS changes the order of some lines when saving content. I don't know if that's intentional.

**Comment by Zukero** [comment]
Not really intentional, but almost necessary.

There's no track kept of line number or order once the data is read in ATCS.

If you alter an element from a JSON file, when you generate the export package for your projact, all data belonging to this file is exported along with it, so that you can overwrite your previous "conversationlist_test.json" with the exported one in the game source tree. This extra data is rewritten from Object data, not source file.

When writing an object, the fields are always written in a fixed order. For example, all dialogues will be saved as "id", "message", "switchToNpc", "replies" and "rewards".

I consider passing all existing content through this process so that they all match the ATCS order once and for all.

**Comment by Zukero** [comment]
I just noticed some classes (Quest for example) do not use the fixed order. This'll be fixed soon.

**Comment by reizy** [comment]
The main point is that order should not be random, because it can result in useless merge conflicts. 
Anyway, Zukero, will you approve/reject this pull request?

**Comment by Zukero** [comment]
I'll end up accepting it after reviewing it.

I'll also take the time at some point to reorganize all content so that
order is consistent and make sure ATCS doesn't mess it up.

**Comment by Zukero** [comment]
@Rijackson could you try re-exporting your changes with the new ATCS, and making sure that your game source folder for this ATCS project matches the latest version of "stoutford_tests", so we can benefit from the preserved order feature, and have cleaner diffs ?
To do so, you can either rebase your "stoutford_tests" branch on mine (conflict resolution ahead...) or create a new branch altogether, and submit a new pull-request.

**Pull request closed without merging**
